# Generated by Django 4.2 on 2024-02-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manelouser',
            name='profile_picture',
            field=models.ImageField(default='static/core/users/default_user_icon.jpg', upload_to='static/core/users/images/<property object at 0x7fae51ca1760>/profile_picture.jpeg'),
        ),
    ]
