# Generated by Django 4.2 on 2024-02-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_manelouser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='manelouser',
            name='profile_picture_path',
            field=models.CharField(default='static/core/users/default_user_icon.jpg', max_length=256),
        ),
        migrations.AlterField(
            model_name='manelouser',
            name='profile_picture',
            field=models.ImageField(default='static/core/users/default_user_icon.jpg', upload_to='static/core/users/images/<property object at 0x7f4a8b6bd6c0>/profile_picture.jpeg'),
        ),
    ]
