# Generated by Django 4.2 on 2024-02-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_manelouser_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manelouser',
            name='profile_picture_path',
        ),
        migrations.AlterField(
            model_name='manelouser',
            name='profile_picture',
            field=models.ImageField(default='default_user_icon.jpg', upload_to='users/images/<property object at 0x7f4420e55800>/'),
        ),
    ]
