# Generated by Django 4.2 on 2024-02-12 14:12

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_manelouser_profile_picture_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manelouser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_user_icon.jpg', upload_to=core.models.ManeloUser.user_directory_path),
        ),
    ]
