# Generated by Django 5.0.2 on 2024-02-22 19:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_manelouser_profile_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="manelouser",
            name="accessibility_settings",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manelouser",
            name="account_creation_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="manelouser",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manelouser",
            name="birthdate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manelouser",
            name="friends",
            field=models.ManyToManyField(blank=True, to="core.manelouser"),
        ),
        migrations.AddField(
            model_name="manelouser",
            name="gender",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="manelouser",
            name="language_preference",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="manelouser",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="manelouser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="manelouser",
            name="social_media_links",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manelouser",
            name="time_zone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="manelouser",
            name="user_status",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="manelouser",
            name="verification_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="manelouser",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manelouser",
            name="interests",
            field=models.ManyToManyField(blank=True, to="core.interest"),
        ),
    ]
